### PR TITLE
Instanthotkeys remove hardcoded font

### PR DESCRIPTION
**Pull request by ppenguin**
remove hardcoded font from the `instantmenu` call. To be used in combination with the `xresources` override capability implemented in https://github.com/instantOS/instantMENU/pull/8.

### CODE REVIEW

**Comment by con-f-use** [comment]
Does instantOS/instantMENU#8 even implement setting the instantMENU font through xresources, or is that already in instantMENU and I just don't know it?

**Comment by paperbenni** [comment]
The hardcoded font is intentional to keep the formatting of the table intact. Without it, the lines have columns with different width. In the long run this might be solved by introducing a tabstop system for instantmenu, but until then I'd like to keep the monospace font

**Comment by ppenguin** [comment]
@paperbenni ...but `instantOS` does config actions in `~/.Xresources` anyway (like for `st.font`), so you could still "force" (or at least influence) the choice of a monospace font? It's not so much the font face which is problematic, but the font size, and this becomes an annoying problem on HiDPI in certain cases.

**Comment by paperbenni** [comment]
That's a good idea, to let the user specify a normal and a monospace font in xresources. I think I'll do that

**Pull request closed without merging**
