### PR TITLE
chmod ./setup files after copying out of the repository

### PR DESCRIPTION
**Pull request by uvera**
Did this to prevent the files in repository from changing permissions

Signed-off-by: Dušan Uverić <dusan.uveric9@gmail.com>

### CODE REVIEW

**Comment by con-f-use** [comment]
> Did this to prevent the files in repository from changing permissions
Sorry, what is your objective here?

**Comment by uvera** [comment]
previously ```find -regex './setup/.*' -exec chmod 755 "{}" \;``` changes the file permissions in the local repo, basically those files get into git staging then which is annoying

**Comment by paperbenni** [comment]
I mean is there anything wrong with having them the correct permission in the repo as well?

**Comment by uvera** [comment]
Not really, now that I think of it, someone should just push the files with new permissions :smile:

**Pull request closed without merging**
